### ISSUE TITLE
Underline Shifts away from the bottom red arrow on certain words passed to msg param

### ISSUE THREAD

**Issue by SachitNayak** [DeltaEvolution/Samaritan#2]
The red arrow shifts to the left and does not stay at the center on long sentences.

**Comment by DeltaEvo** [comment]
Yes I did it on purpose -> watch this video https://youtu.be/hTWDqEc4_N8?t=2m22s 
but if you want i can add an option to disable this behavior

**Comment by 4yx** [comment]
@DeltaEvo yeah, it would be better if you could add such an option.

**Comment by SachitNayak** [comment]
> Yes I did it on purpose -> watch this video https://youtu.be/hTWDqEc4_N8?t=2m22s
> but if you want i can add an option to disable this behavior

I see. Alright. I think this issue can be closed now.
